[package]
name = "count_to_a_million"
version = "0.1.0"
authors = ["o0Ignition0o <jeremy.lempereur@gmail.com>"]
edition = "2018"

[dependencies]
nitox = {git= "http://github.com/yellowinnovation/nitox", branch="develop"}
futures = "0.1.25"
tokio = "0.1.13"
